# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-09 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='token',
            name='uid',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
